//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Пользователи
    {
        public int Код_пользователя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Тип_учетной_записи { get; set; }
    }
}
