//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Трудовые_договоры
    {
        public int Код_договора { get; set; }
        public int Номер_договора { get; set; }
        public System.DateTime Дата_заключения { get; set; }
        public decimal Заработная_плата { get; set; }
        public System.DateTime Дата_расторжения { get; set; }
        public int Код_сотрудника { get; set; }
    
        public virtual Сотрудники Сотрудники { get; set; }
    }
}
