//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData
{
    public partial class ТрудоваяКнигаView
    {
        public int Код_трудовой_книги { get; set; }
        public int Табельный_номер { get; set; }
        public string Наименование_отдела { get; set; }
        public string Наименование_должности { get; set; }
        public string Примечание { get; set; }
        public System.DateTime Дата_начала { get; set; }
        public System.DateTime Дата_окончания { get; set; }
        public int Код_должности { get; set; }
        public int Код_отдела { get; set; }
    }
}
