//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaveData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Штатное_расписание
    {
        public int Код_расписания { get; set; }
        public int Код_отдела { get; set; }
        public int Код_должности { get; set; }
        public string Тип_расписания { get; set; }
        public int Количество_вакансий { get; set; }
        public string Свободно { get; set; }
    
        public virtual Должности Должности { get; set; }
        public virtual Отделы Отделы { get; set; }
    }
}
